// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvidMkfjCvkD-m2Swr8K6csv8NObIhR54',
    appId: '1:46977764150:web:bbe4ca2d571e90941e0197',
    messagingSenderId: '46977764150',
    projectId: 'insta-5105f',
    authDomain: 'insta-5105f.firebaseapp.com',
    storageBucket: 'insta-5105f.appspot.com',
    measurementId: 'G-F7DK5F9ENF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRb21YPmKSvy9azfuFrZF2MwaXsuViDOA',
    appId: '1:46977764150:android:79440f14b3e08c4f1e0197',
    messagingSenderId: '46977764150',
    projectId: 'insta-5105f',
    storageBucket: 'insta-5105f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkUUfh65-Uy7-btrrCDdQRAfjWcG70MGw',
    appId: '1:46977764150:ios:9de8641d6efcc02f1e0197',
    messagingSenderId: '46977764150',
    projectId: 'insta-5105f',
    storageBucket: 'insta-5105f.appspot.com',
    androidClientId: '46977764150-c78niu1hi91n84ff41p64cvcnfv6d7p6.apps.googleusercontent.com',
    iosClientId: '46977764150-tjee0mh6chd8nakt4dn158nv02v9kpf4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nstagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkUUfh65-Uy7-btrrCDdQRAfjWcG70MGw',
    appId: '1:46977764150:ios:0bd9d508aaa4151d1e0197',
    messagingSenderId: '46977764150',
    projectId: 'insta-5105f',
    storageBucket: 'insta-5105f.appspot.com',
    androidClientId: '46977764150-c78niu1hi91n84ff41p64cvcnfv6d7p6.apps.googleusercontent.com',
    iosClientId: '46977764150-qtl3ivbh4hkk846oksirqup28uvfmvjm.apps.googleusercontent.com',
    iosBundleId: 'com.example.nstagram.RunnerTests',
  );
}
